<?php

namespace TBSBundle\Repository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends \Doctrine\ORM\EntityRepository
{

	public function findSentBaskets()
    {
        $query = $this->getEntityManager()
                        ->createQuery("
	            SELECT b FROM TBSBundle:Basket b WHERE b.bStatus LIKE 'sent'"
                        );
        //$query->setParameter('b_status', $b_status.'%');
        return $query->getResult();
    }

}
