<?php

namespace TBSBundle\Repository;

/**
 * OrderlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderlineRepository extends \Doctrine\ORM\EntityRepository
{
}
