<?php

namespace TBSBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	public function findUserByUsername($username)
    {
        $query = $this->getEntityManager()
                        ->createQuery("
	            SELECT s FROM TBSBundle:User s WHERE s.username LIKE :username"
                        );
        $query->setParameter('username', $username.'%');
        return $query->getResult();
    }

}
