tbs_index:
    path:     /
    defaults: { _controller: TBSBundle:Default:index }

tbs_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }

tbs_delete_list_user:
    path:     /deletelistuser
    defaults: { _controller: TBSBundle:Default:delete }

tbs_delete_user:
    path:     /{id}/deleteuser
    defaults: { _controller: TBSBundle:Default:deleteUser }

tbs_add_basket:
    path:     /addbasket
    defaults: { _controller: TBSBundle:Basket:addInBasket }

tbs_add_orderline:
    path:     /{id}/addorder
    defaults: { _controller: TBSBundle:Orderline:addInOrderline }

tbs_stock:
    path:     /stock
    defaults: { _controller: TBSBundle:Stock:index }

tbs_add_stock:
    path:     /addstock
    defaults: { _controller: TBSBundle:Stock:add }

tbs_product:
    path:     /product
    defaults: { _controller: TBSBundle:Product:index }

tbs_add_product:
    path:     /addproduct
    defaults: { _controller: TBSBundle:Product:add }