tbs_index:
    path:     /
    defaults: { _controller: TBSBundle:Default:index }

tbs_ros:
    path:     /ros
    defaults: { _controller: TBSBundle:Default:ros }

tbs_indexca:
    path:     /{id}/indexca
    defaults: { _controller: TBSBundle:Default:indexca }

tbs_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }

tbs_stats:
    path:     /stats
    defaults: { _controller: TBSBundle:Default:stats}

tbs_delete_list_user:
    path:     /deletelistuser
    defaults: { _controller: TBSBundle:Default:delete }

tbs_delete_user:
    path:     /{id}/deleteuser
    defaults: { _controller: TBSBundle:Default:deleteUser }

tbs_add_basket:
    path:     /{id}/addbasket
    defaults: { _controller: TBSBundle:Basket:addInBasket }

tbs_add_orderline:
    path:     /{id}/addorder
    defaults: { _controller: TBSBundle:Orderline:addInOrderline }

tbs_stock:
    path:     /stock
    defaults: { _controller: TBSBundle:Stock:index }

tbs_add_stock:
    path:     /addstock
    defaults: { _controller: TBSBundle:Stock:add }

tbs_stocks:
    path:     /stocks
    defaults: { _controller: TBSBundle:Stock:stocks }

tbs_edit_stock:
    path:     /{id}/editstock
    defaults: { _controller: TBSBundle:Stock:edit }

tbs_delete_stock:
    path:     /{id}/deletestock
    defaults: { _controller: TBSBundle:Stock:delete }

tbs_product:
    path:     /product
    defaults: { _controller: TBSBundle:Product:index }

tbs_add_product:
    path:     /addproduct
    defaults: { _controller: TBSBundle:Product:add }

tbs_products:
    path:     /products
    defaults: { _controller: TBSBundle:Product:products }

tbs_edit_product:
    path:     /{id}/editproduct
    defaults: { _controller: TBSBundle:Product:edit }

tbs_delete_product:
    path:     /{id}/deleteproduct
    defaults: { _controller: TBSBundle:Product:delete }

tbs_delete_basket:
    path:     /{id}/deletebasket
    defaults: { _controller: TBSBundle:Basket:delete }

tbs_delete_orderline:
    path:     /{id}/deleteorder
    defaults: { _controller: TBSBundle:Orderline:delete }

tbs_confirmed_basket:
    path:     /{id}/validbasket
    defaults: { _controller: TBSBundle:Basket:confirm }